name: nexterp
services:
  nexterp:
    image: kaysar12/nexterp:1.3
    user: root
    deploy:
      resources:
        reservations:
          memory: "512M"
    depends_on:
      db-nexterp:
        condition: service_healthy
    environment:
      - HOST=db-nexterp
      - PASSWORD=smartyourlife
      - USER=nextzen
    ports:
      - target: 8069
        published: "27000"
        protocol: tcp
      - target: 8072
        published: "19000"
        protocol: tcp
    tty: true
    restart: unless-stopped
    volumes:
      - /NextZen/Apps/Default/$AppID/web-data:/var/lib/odoo
      - /NextZen/Apps/Default/$AppID/config:/etc/odoo
      - /NextZen/Apps/Default/$AppID/addons:/mnt/extra-addons
    x-casaos:
      ports:
        - container: "8069"
          description:
            en_us: WebUI HTTP Port
            zh_cn: WebUI HTTP 端口
        - container: "8072"
          description:
            en_us: Chat Port
            zh_cn: Chat Port
      volumes:
        - container: /var/lib/odoo
          description:
            en_us: NextErp webdata directory.
        - container: /etc/odoo
          description:
            en_us: NextErp config directory.
        - container: /mnt/extra-addons
          description:
            en_us: NextErp addons directory.
    container_name: nexterp
  db-nexterp:
    container_name: db-nexterp
    image: postgres:16
    user: root
    deploy:
      resources:
        reservations:
          memory: "512M"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=smartyourlife
      - POSTGRES_USER=nextzen
    restart: unless-stopped
    volumes:
      - /NextZen/Apps/Default/$AppID/database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "nextzen" ]
      interval: 10s
      timeout: 5s
      retries: 5
    x-casaos:
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: Database data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
    - "386"
    - mips64le
    - ppc64le
    - s390x
  main: nexterp
  author: NextZenOS Team
  category: Developer
  description:
    en_us: NextERP is a software tools that include customer relationship management, e-commerce, billing, accounting, manufacturing, warehouse, project management, and inventory management.
  developer: NextZenOS
  icon: https://git.nextzenos.com/CDN/Images/raw/commit/ac64cfb95de16732bff7a4732cea4982a7acfe99/NextERP/NextERP2-removebg-preview.png
  screenshot_link:
    - https://odoocdn.com/web/image/9181393/Leads%20Analysis%20-%20Odoo.png?access_token=9566a404-561d-4a94-b600-4a163fbaedd7
    - https://easypanel.io/assets/images/screenshot-848927db3f2bab2af809bb7a7753c00a.png
    - https://www.images.cybrosys.com/blog/Uploads/BlogImage/how-to-schedule-a-new-meeting-with-odoo-15-calendar-module-3.png
    - https://www.confianzit.com/cit-blog/wp-content/uploads/2023/11/Odoo-17-Accounting-dashboard.png
  tagline:
    en_us: Elevate your business
  thumbnail: https://creatives.me/wp-content/uploads/2024/06/Odoo-01-1.jpg
  tips: {}
  title:
    en_us: Nexterp
  index: /
  port_map: "27000"
