# Configuration for odoo setup

# Name of the big-bear-odoo application
name: nexterp

# Service definitions for the big-bear-odoo application
services:
  # Service name: big-bear-odoo
  # This section defines the main Odoo service
  nexterp:
    # Name of the container
    container_name: nexterp # Specifies the container instance name for identification

    # Image to be used for the container
    image: kaysar12/nexterp:1.3 # Docker image for Odoo version 17

    # Container restart policy
    restart: unless-stopped # Restart policy to ensure service recovery

    # User to run the container as
    user: root # Specifies running the container as root

    # Volumes to be mounted to the container
    volumes:
      - /NextZen/Apps/Default/NextZenERP/config:/etc/odoo
      - /NextZen/Apps/Default/NextERP/addons:/mnt/extra-addons

    # Ports mapping between host and container
    ports:
      - "8069:8069"

    # Environment variables
    environment:
      - HOST=nexterp-db # Database host
      - USER=nextzen # Database username
      - PASSWORD=nextzen # Database password

    # Networks to be attached to the container
    networks:
      - nexterp_network # Specifies network attachment for internal communication

    # CasaOS specific configuration for environment variables and volumes
    x-casaos:
      envs:
        - container: HOST
          description:
            en_us: "Container Host: nexterp-db"
        - container: USER
          description:
            en_us: "Container User: nextzen"
        - container: PASSWORD
          description:
            en_us: "Container Password: nextzen"
      volumes:
        - container: /etc/odoo
          description:
            en_us: "Container Path: /etc/odoo"
        - container: /mnt/extra-addons
          description:
            en_us: "Container Path: /mnt/extra-addons"
      ports:
        - container: "8069"
          description:
            en_us: "Container Port: 8069"

  # Database service for Odoo
  nexterp-db:
    container_name: nexterp-db # Database container name
    image: postgres:16 # PostgreSQL version 15 Docker image
    user: root # Runs as root user
    environment:
      - POSTGRES_USER=nextzen # Database user
      - POSTGRES_PASSWORD=nextzen # Database password
      - POSTGRES_DB=postgres # Database name
    restart: unless-stopped # Restart policy for the database
    volumes: -/NextZen/Apps/Default/NextZenERP/db-data:/var/lib/postgresql/data # Mounts PostgreSQL data directory
    networks:
      - nexterp_network # Attached network for internal communication

    # CasaOS specific configuration for database volumes and environment
    x-casaos:
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
      envs:
        - container: POSTGRES_USER
          description:
            en_us: "Container User: nextzen"
        - container: POSTGRES_PASSWORD
          description:
            en_us: "Container Password: nextzen"
        - container: POSTGRES_DB
          description:
            en_us: "Container Database: postgres"

# Network definition for the big-bear-odoo application
networks:
  nexterp_network:
    driver: bridge # Specifies network driver as bridge

# CasaOS specific configuration
x-casaos:
  # Supported CPU architectures for the application
  architectures:
    - amd64
    - arm64
  # Main service of the application
  main: nexterp
  # Comprehensive description of Odoo
  description:
    en_us: Open-source business management software suite designed to streamline various aspects of business operations. With its modular structure, users can choose and integrate specific applications such as accounting, inventory, and sales. Odoo provides a user-friendly interface, scalability for businesses of all sizes, and is available in both community (free) and enterprise editions. Its integrated approach and customization options make it a popular choice for comprehensive ERP (Enterprise Resource Planning) solutions.
  # Short description or tagline
  tagline:
    en_us: Open-source business management software with modular applications for streamlined operations.
  # Developer's name or identifier
  developer: "Nextzen"
  # Author of this configuration
  author: Nextzen
  # Icon for the application
  icon: https://cdn.jsdelivr.net/gh/bigbeartechworld/big-bear-casaos/Apps/odoo/logo.jpg
  # Thumbnail image (currently empty)
  thumbnail: ""
  # Title in English
  title:
    en_us: NextErp
  # Application category
  category: Developer
  # Port mapping information
  port_map: "8069"
  tips:
    before_install:
      en_us: |
        Documentation: https://community.bigbeartechworld.com/t/added-odoo-to-bigbearcasaos/1115?u=dragonfire1119
